name: Build Windows Executable and MSI

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msi

      - name: Install frontend dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Install Tauri CLI
        run: npm install -g @tauri-apps/cli

      - name: Build Tauri app for Windows
        run: tauri build --target x86_64-pc-windows-msi

      - name: Upload Windows .exe and .msi artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build-artifacts
          path: |
            src-tauri/target/x86_64-pc-windows-msi/release/bundle/msi/*.msi
            src-tauri/target/x86_64-pc-windows-msi/release/bundle/msi/*.exe 